version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: FinTrace/Dockerfile
    ports:
      - "80:80"  # Expor a aplicação Angular na porta 80
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"  # Expor a aplicação Spring Boot na porta 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge
