# Usar a imagem do OpenJDK 17 como base
FROM openjdk:17-jdk-slim AS build

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o arquivo pom.xml e fazer o download das dependências
COPY backend/pom.xml ./
RUN mvn dependency:go-offline

# Copiar o código da aplicação
COPY backend/src /app/src

# Construir o aplicativo Spring Boot
RUN mvn clean package -DskipTests

# Etapa final: usar a imagem JRE para rodar a aplicação
FROM openjdk:17-jre-slim

# Definir a variável de ambiente para a JAR
ARG JAR_FILE=/app/target/fintrace-0.0.1-SNAPSHOT.jar

# Copiar o JAR gerado da etapa anterior
COPY --from=build /app/target/fintrace-0.0.1-SNAPSHOT.jar /app/backend.jar

# Expor a porta em que o Spring Boot vai rodar
EXPOSE 8080

# Comando para rodar a aplicação Spring Boot
ENTRYPOINT ["java", "-jar", "/app/backend.jar"]
