# Etapa 1: Construir a aplicação Angular
FROM node:16 AS build

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY FinTrace/package*.json ./

# Instalar as dependências do Angular
RUN npm install

# Copiar o restante do código da aplicação
COPY FinTrace/ ./

# Criar o build da aplicação Angular
RUN npm run build --prod

# Etapa 2: Servir a aplicação com um servidor NGINX
FROM nginx:alpine

# Copiar os arquivos de build para o NGINX
COPY --from=build /app/dist/fin-trace /usr/share/nginx/html

# Copiar o arquivo de configuração do NGINX com proxy reverso
COPY FinTrace/nginx.conf /etc/nginx/nginx.conf

# Expor a porta 80 (NGINX)
EXPOSE 80

# Comando para rodar o NGINX
CMD ["nginx", "-g", "daemon off;"]

